Try to add duration
We-Gold/gpxjs pull request #12
Opened 2024-11-19 09:28 UTC by Its-Just-Nans

May fix https://github.com/We-Gold/gpxjs/issues/11

2024-11-19 09:33 UTC, Its-Just-Nans commented
Apparently it could be better to apply threeshold with 10 seconds check


> https://support.strava.com/hc/en-us/articles/115001188684-Moving-Time-Speed-and-Pace-Calculations
> What constitutes a rest? Is it when you rest for 1, 3, 10, or 20 seconds? And what does your speed have to fall below for you to be considered at rest? One second might capture too many false positives, and 20 seconds may be too strict. One calculation isn't necessarily correct or incorrect, but we feel we use standards that most athletes would agree upon.

2024-11-19 15:25 UTC, We-Gold commented
Can you add some comments to explain some of the calculations and constants in the `calculateDuration` function? I recognize that not all the other functions in _math_helpers_ are well commented, but in this case, it is important since you have some unexplained numbers. If someone looks at the code in the future, they may wonder why you divide by 1000 or have a threshold of exactly 0.00055.

The Strava example seems specific to GPX files from activity trackers (e.g. a GPS-enabled watch) since it assumes human movement. It's fine to calculate a thresholded version of the durations based on the Strava information, but that should be in addition to the current duration information that doesn't assume human movement.

In the future, it would be nice to add an option object to pass into the main `parseGPX` function, to allow a user to specify what they want calculated or maybe specific thresholds. Since that feature doesn't currently exist, I'd prefer to not make the code too opinionated, and anything opinionated should be in addition to the expected calculations.

2024-11-19 17:24 UTC, Its-Just-Nans commented
I updated the code

2024-11-20 14:25 UTC, We-Gold commented on lib/math_helpers.ts
> +				console.log(avgSpeed)
Remove console.log

2024-11-20 14:32 UTC, We-Gold requested changes
Aside from the two specific comments, the options object needs to be documented in the readme. It needs its own section, so I suggest switching the old heading "Documentation" to "Types" and adding a new section above that section for "Options". Also, make sure to show an example of how to pass them in.

The Duration type and the changes to other types also need to be added to the types section of the readme documentation (currently called documentation).

2024-11-20 14:32 UTC, We-Gold commented on lib/parse.ts
> +const DEFAULT_THRESHOLD = 0.000215 // m/ms - 0.215 m/s - 774000 km/h
Move DEFAULT_THRESHOLD and DEFAULT_OPTIONS to a new file, like options.ts.

2024-11-20 14:32 UTC, We-Gold commented on lib/parse.ts
> +	removeEmptyFields: boolean = true
Pass in options object to `parseGPX`, the same as with `parseGPXWithCustomParser`. Then merge this with the default options to fill in any unspecified values.

2024-11-20 14:50 UTC, We-Gold commented on README.md
> +You can also run `parseGPX()` with custom options for more control over the parsing process. See [options.ts](./lib/options.ts) for more details.
The individual options need to be explained either in the README or the options.ts file you link to. If you do it in the file, comments on each line explaining each option should suffice for now.

2024-11-20 15:22 UTC, We-Gold commented
Since the code looks good, I will test it locally later (hopefully today). If everything goes well, I can approve and merge it.

2024-11-21 15:46 UTC, We-Gold approved these changes
After testing locally, the calculations seem to be correct, and I didn't discover any errors. All the tests passed.

2024-11-21 15:47 UTC, merged